"""Allow nullable franchise ids

Revision ID: 008a97502e4b
Revises: 3de1319423e3
Create Date: 2024-11-20 14:30:43.196534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008a97502e4b'
down_revision = '3de1319423e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('franchise_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('franchise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
