"""Create database

Revision ID: 3de1319423e3
Revises: 
Create Date: 2024-11-20 14:10:14.831320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de1319423e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('headshot', sa.String(length=255), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=False),
    sa.Column('birth_province', sa.String(length=100), nullable=False),
    sa.Column('birth_country', sa.String(length=100), nullable=False),
    sa.Column('height_in_inches', sa.Integer(), nullable=False),
    sa.Column('weight_in_pounds', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('goals_per_game', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('shooting_pct', sa.Float(), nullable=False),
    sa.Column('avg_toi', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('raw_tricode', sa.String(length=3), nullable=False),
    sa.Column('tricode', sa.String(length=3), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(length=20), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=False),
    sa.Column('home_road_flag', sa.String(length=1), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('toi', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name='fk_player_player_id'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name='fk_team_team_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster')
    op.drop_table('game_log')
    op.drop_table('team')
    op.drop_table('player')
    # ### end Alembic commands ###
