"""Add PlayerRank Model

Revision ID: 570f3bb42b31
Revises: 008a97502e4b
Create Date: 2024-12-06 19:29:31.245405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570f3bb42b31'
down_revision = '008a97502e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_rank')
    # ### end Alembic commands ###
