"""change rank type

Revision ID: 8191fd9127da
Revises: c9cbd1fb9273
Create Date: 2024-12-06 23:37:24.407263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8191fd9127da'
down_revision = 'c9cbd1fb9273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_rank', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_rank', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
