"""add game_log table

Revision ID: 84633bcbbcfe
Revises: 9b06190bd404
Create Date: 2024-10-13 14:31:27.911940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84633bcbbcfe'
down_revision = '9b06190bd404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(length=20), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=False),
    sa.Column('home_road_flag', sa.String(length=1), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('toi', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    # ### end Alembic commands ###
