"""Initial migration.

Revision ID: 9395034152d3
Revises: 84633bcbbcfe
Create Date: 2024-10-13 15:45:06.119908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9395034152d3'
down_revision = '84633bcbbcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('headshot', sa.String(length=255), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=False),
    sa.Column('birth_province', sa.String(length=100), nullable=False),
    sa.Column('birth_country', sa.String(length=100), nullable=False),
    sa.Column('height_in_inches', sa.Integer(), nullable=False),
    sa.Column('weight_in_pounds', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('goals_per_game', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('shooting_pct', sa.Float(), nullable=False),
    sa.Column('avg_toi', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(length=20), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=False),
    sa.Column('home_road_flag', sa.String(length=1), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('toi', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    op.drop_table('player')
    # ### end Alembic commands ###
