"""Added new columsn to Player.

Revision ID: 9b06190bd404
Revises: 
Create Date: 2024-10-13 13:42:11.087832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b06190bd404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('headshot', sa.String(length=255), nullable=False),
    sa.Column('birth_city', sa.String(length=100), nullable=False),
    sa.Column('birth_province', sa.String(length=100), nullable=False),
    sa.Column('birth_country', sa.String(length=100), nullable=False),
    sa.Column('height_in_inches', sa.Integer(), nullable=False),
    sa.Column('weight_in_pounds', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('goals_per_game', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('power_play_goals', sa.Integer(), nullable=False),
    sa.Column('shooting_pct', sa.Float(), nullable=False),
    sa.Column('avg_toi', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
