name: CI/CD Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            source venv/bin/activate
            export FLASK_CONFIG=testing
            pytest

        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.13.15
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}