name: CI/CD Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            source venv/bin/activate
            echo "FLASK_ENV=production
            CONFIG_NAME=production
            DATABASE_URL=postgresql://ub22a0vvtepq9a:pf1d1c55a7df90189519ec551ebb0f6af8dcd3665afe26a7dc7196c45b2450a0a@cb5ajfjosdpmil.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfosdmrmvl3r71
            SECRET_KEY='72c0f6776effb1957d13fc9027a6cbc3'" >> .env
            pytest

        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.13.15
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}