name: CI/CD Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            source venv/bin/activate
            pytest

        - name: Authenticate with Heroku
          run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

        - name: Push to Heroku
          run: |
            git remote | grep heroku && git remote remove heroku || true
            heroku git:remote -a your-app-name
            git push heroku main
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}